# Generated by Django 5.2 on 2025-07-10 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_deliverycharge'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='home_components/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_components', to='products.category')),
            ],
            options={
                'verbose_name': 'Homepage Component',
                'verbose_name_plural': 'Homepage Components',
            },
        ),
    ]
