# Generated by Django 5.2 on 2025-07-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_deliverycharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommercecheckouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.CharField(default='{}', max_length=1000)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=255)),
                ('delivery_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommercecheckouts', to='products.deliverycharge')),
            ],
        ),
    ]
