# Generated by Django 5.2 on 2025-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercecheckouts',
            name='bkash_trx_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
