# Generated by Django 5.2 on 2025-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ecommercecheckouts_bkash_trx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercecheckouts',
            name='delivery_options',
            field=models.CharField(default='Cash on Delivery', max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercecheckouts',
            name='items_json',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
