# Generated by Django 5.2 on 2025-08-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ecommercecheckouts_delivery_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommercecheckouts',
            old_name='delivery_options',
            new_name='payment_method',
        ),
    ]
