# Generated by Django 5.2 on 2025-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_delivery_options_ecommercecheckouts_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecheckouts',
            name='bkash_trx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
