# Generated by Django 5.2 on 2025-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_name_alter_productimage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, help_text="Unique identifier for this image (e.g., 'front_view', 'side_view').", max_length=255, null=True),
        ),
    ]
