# Generated by Django 5.2 on 2025-07-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'sku')},
        ),
    ]
