# Generated by Django 5.2 on 2025-07-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sku',
        ),
    ]
