# Generated by Django 5.2 on 2025-07-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
