# Generated by Django 5.2 on 2025-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
