# Generated by Django 5.2 on 2025-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, help_text="A unique name for this image within the product (e.g., 'front_view', 'detail_shot').", max_length=255),
        ),
    ]
