# Generated by Django 5.2 on 2025-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, help_text="A unique name for this image within the product (e.g., 'front_view', 'detail_shot').", max_length=255, null=True),
        ),
    ]
